// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V3_4_4_59817
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class ObjectData : IMutableObjectData
    {
        public System.Nullable<int> EntryID { get; set; }
        public System.Nullable<uint> DynamicFlags { get; set; }
        public System.Nullable<float> Scale { get; set; }
    }
}

