// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_8_0_69137.UpdateFields.V3_80_2_69137
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class AreaTriggerOrbit : IAreaTriggerOrbit
    {
        public Vector3 Center { get; set; }
        public System.Nullable<float> Radius { get; set; }
        public System.Nullable<float> InitialAngle { get; set; }
        public System.Nullable<float> BlendFromRadius { get; set; }
        public System.Nullable<int> ExtraTimeForBlending { get; set; }
        public System.Nullable<bool> CounterClockwise { get; set; }
    }
}

