// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_8_0_69137.UpdateFields.V3_80_2_69137
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class AreaTriggerCylinder : IAreaTriggerCylinder
    {
        public System.Nullable<float> Radius { get; set; }
        public System.Nullable<float> RadiusTarget { get; set; }
        public System.Nullable<float> Height { get; set; }
        public System.Nullable<float> HeightTarget { get; set; }
        public System.Nullable<float> LocationZOffset { get; set; }
        public System.Nullable<float> LocationZOffsetTarget { get; set; }
    }
}

