// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_8_0_69137.UpdateFields.V3_80_2_69137
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class SkillInfo : ISkillInfo
    {
        public System.Nullable<ushort>[] SkillLineID { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillStep { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillRank { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillStartingRank { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillMaxRank { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<short>[] SkillTempBonus { get; } = new System.Nullable<short>[256];
        public System.Nullable<ushort>[] SkillPermBonus { get; } = new System.Nullable<ushort>[256];
    }
}

