// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_8_0_69137.UpdateFields.V3_80_2_69137
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class StablePetInfo : IStablePetInfo
    {
        public System.Nullable<uint> PetSlot { get; set; }
        public System.Nullable<uint> PetNumber { get; set; }
        public System.Nullable<uint> CreatureID { get; set; }
        public System.Nullable<uint> DisplayID { get; set; }
        public System.Nullable<uint> ExperienceLevel { get; set; }
        public System.Nullable<byte> PetFlags { get; set; }
        public System.Nullable<byte> Field_96 { get; set; }
        public System.Nullable<uint> Specialization { get; set; }
        public string Name { get; set; }
    }
}

