// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_8_0_69137.UpdateFields.V3_80_2_69137
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class VisualAnim : IVisualAnim
    {
        public System.Nullable<uint> AnimationDataID { get; set; }
        public System.Nullable<uint> AnimKitID { get; set; }
        public System.Nullable<uint> AnimProgress { get; set; }
        public System.Nullable<bool> IsDecay { get; set; }
    }
}

