using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V3_4_3_51666
{
    public class SpellFlatModByLabel : ISpellFlatModByLabel
    {
        public int ModIndex { get; set; }
        public int ModifierValue { get; set; }
        public int LabelID { get; set; }
    }
}

