using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V3_4_3_51666
{
    public class TraitEntry : ITraitEntry
    {
        public int TraitNodeID { get; set; }
        public int TraitNodeEntryID { get; set; }
        public int Rank { get; set; }
        public int GrantedRanks { get; set; }
    }
}

