// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V3_4_5_61815
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class CharacterRestriction : ICharacterRestriction
    {
        public int Field_0 { get; set; }
        public int Field_4 { get; set; }
        public int Field_8 { get; set; }
        public uint Type { get; set; }
    }
}

