// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V3_4_5_61815
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class PlayerDataElement : IPlayerDataElement
    {
        public float FloatValue { get; set; }
        public long Int64Value { get; set; }
        public uint Type { get; set; }
    }
}

