using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V1_15_0_52146
{
    public class ObjectData : IMutableObjectData
    {
        public System.Nullable<int> EntryID { get; set; }
        public System.Nullable<uint> DynamicFlags { get; set; }
        public System.Nullable<float> Scale { get; set; }
    }
}

