// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_80_2_69137.UpdateFields.V3_80_2_69137
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class AreaTriggerSplineCalculator : IAreaTriggerSplineCalculator
    {
        public DynamicUpdateField<System.Nullable<Vector3>> Points { get; } = new DynamicUpdateField<System.Nullable<Vector3>>();
        public System.Nullable<bool> Catmullrom { get; set; }
    }
}

