// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_80_2_69137.UpdateFields.V3_80_2_69137
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class UnitChannel : IUnitChannel
    {
        public int SpellID { get; set; }
        public int SpellXSpellVisualID { get; set; }
        public uint StartTimeMs { get; set; }
        public uint Duration { get; set; }
    }
}

