using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V1_14_4_51146
{
    public class ItemMod : IItemMod
    {
        public int Value { get; set; }
        public byte Type { get; set; }
    }
}

