using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_5_61815.UpdateFields.V3_4_1_47014
{
    public class Research : IResearch
    {
        public short ResearchProjectID { get; set; }
    }
}

